apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: andreigordeev-online
  namespace: default
spec:
  secretName: andreigordeev-online-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: andreigordeev.online
  dnsNames:
    - andreigordeev.online
    - www.andreigordeev.online