apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: andreigordeev-online
spec:
  secretName: andreigordeev-online-tls
  issuerRex:
    name: letsencrypt-prod
  commonName: andreigordeev.online
  dnsNames:
    - www.andreigordeev.online